# set -g default-terminal "xterm-256color"
set -g repeat-time 800

set -g prefix C-s
set -g mouse on

bind r source-file ~/.config/tmux/tmux.conf

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 1
bind -r J resize-pane -D 1
bind -r K resize-pane -U 1
bind -r L resize-pane -R 1

set -g status-position top
set -g status-bg yellow
set -g status-fg white

set -s escape-time 100


setw -g mode-keys vi

unbind -T copy-mode-vi v
unbind -T copy-mode-vi V
unbind -T copy-mode-vi C-v
unbind -T copy-mode-vi y

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi v send-keys -X begin-selection \; send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind -T copy-mode-vi _ send-keys -X back-to-indentation

bind -T copy-mode-vi C-[ send-keys -X clear-selection


bind -T command-prompt C-[ send-keys -X abort

set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
run "~/.tmux/plugins/tpm/tpm"

